//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.14 at 09:02:32 PM EDT 
//


package pvt.hrk.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "channel"
})
@XmlRootElement(name = "rss")
public class Rss {

    @XmlElement(required = true)
    protected Channel channel;
   /* @XmlAttribute(name = "dc")
    protected String dc;
    @XmlAttribute(name = "g-core")
    protected String gCore;
    @XmlAttribute(name = "geo")
    protected String geo;
    @XmlAttribute(name = "version")
    protected Integer version;*/

   
    public Channel getChannel() {
        return channel;
    }
    public void setChannel(Channel value) {
        this.channel = value;
    }
    /*  public String getDc() {
        return dc;
    }
    public void setDc(String value) {
        this.dc = value;
    }
    public String getGCore() {
        return gCore;
    }

    public void setGCore(String value) {
        this.gCore = value;
    }

    public String getGeo() {
        return geo;
    }

    public void setGeo(String value) {
        this.geo = value;
    }

    public Integer getVersion() {
        return version;
    }
    public void setVersion(Integer value) {
        this.version = value;
    }*/
	

    
}
